services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888
    volumes:
      - zookeeper-data1:/var/lib/zookeeper/data
      - zookeeper-log1:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka1
    depends_on:
      - zookeeper1
    ports:
      - "9092:9092" # For external connections using PLAINTEXT_HOST
      - "29092:29092" # For internal Docker connections
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data1:/var/lib/kafka/data

  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile.PySpark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080" # Spark UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ./spark/jobs:/app/spark_jobs
      - ./spark/artifacts:/app/artifacts 
      - spark-ivy-cache:/root/.ivy2
      - check-point:/tmp/kafka-syslog-checkpoint

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile.PySpark
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./spark/jobs:/app/spark_jobs
      - ./spark/artifacts:/app/artifacts
      - spark-ivy-cache:/root/.ivy2
      - check-point:/tmp/kafka-syslog-checkpoint
  
  kafka-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile.Producer
    container_name: kafka-producer
    depends_on:
      - kafka1
    volumes:
      - ./producer:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:29092

volumes:
  zookeeper-data1:
  zookeeper-log1:
  kafka-data1:
  spark-ivy-cache:
  check-point: